on:
  push:
    tags:
    - releases/gel-auth/v*

name: Release gel-auth

jobs:
  test_and_publish:
    name: Test and publish
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      # checkout and env setup
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Build the nix shell
        run: nix develop --command just --version

      # test
      - name: Test
        run: nix develop --command just test

      # verify that git tag matches cargo version
      - run: |
          set -x
          cargo_version="$(cargo metadata --format-version 1 \
            | jq -r '.packages[] | select(.name=="gel-auth") | .version')"
          tag_version="${GITHUB_REF#refs/tags/releases/gel-auth/v}"
          test "$cargo_version" = "$tag_version"

      - working-directory: ./gel-auth
        run: |
          nix develop --command cargo publish --token=${{ secrets.CARGO_REGISTRY_TOKEN }}
